import { test, expect } from '@playwright/test';
test('Actual results, filters, tabs and downloads work', async ({page})=>{
  const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByTestId('metric-quality')).toHaveText('31.6%');
  await expect(page.getByTestId('metric-pressure')).toHaveText('+47.9%');
  await page.locator('#region').selectOption('GBR');
  await expect(page.getByTestId('metric-pressure')).toHaveText('+210.7%');
  await page.getByRole('button',{name:'SSP1–2.6',exact:true}).click();
  await expect(page.getByTestId('metric-pressure')).toHaveText('+209.6%');
  await page.getByRole('button',{name:'Switch language',exact:true}).click();
  await page.getByRole('button',{name:'Heatwaves & exposure',exact:true}).click();
  await expect(page.getByText('Historical analysis: fixed 54-tracer MPEI')).toBeVisible();
  await page.getByRole('button',{name:'Conservation',exact:true}).click();
  await expect(page.getByText('Effective bootstrap replicates')).toBeVisible();
  await expect(page.getByText('991',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Data & provenance',exact:true}).click();
  await page.getByRole('textbox',{name:'Search source files'}).fill('Table_S5');
  await expect(page.locator('.source-card')).toHaveCount(1);
  const sourceDownload=page.waitForEvent('download');
  await page.getByRole('link',{name:'Download Supplementary_Table_S5_20260906.csv'}).click();
  expect((await sourceDownload).suggestedFilename()).toBe('Supplementary_Table_S5_20260906.csv');
  await page.getByRole('button',{name:'Export data',exact:true}).click();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Current-scenario regional CSV'}).click();
  expect((await download).suggestedFilename()).toContain('ssp126_2050');
  expect(errors).toEqual([]);
});
test('Responsive layout has no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  await expect(page.getByTestId('metric-quality')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('button',{name:'数据与溯源',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Search source files'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
