import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Check, ChevronDown, Database, ExternalLink, FileCheck2, FlaskConical, Globe2, Layers3, LayoutDashboard, Leaf, Menu, Search, ShieldCheck, ThermometerSun, Waves, X } from 'lucide-react';
import { ReefMap, IntervalChart, ScenarioBars } from './Charts';
import { SCENARIOS, REGIONS, findResult, formatPct, intervalIncludesZero, rowsToCsv } from './lib.mjs';
import type { DemoData, MapCell, Future, Metric } from './types';

type View = 'overview' | 'future' | 'historical' | 'conservation' | 'data' | 'methods';
const scenarios: Record<string,string> = {ssp126_2050:'SSP1–2.6',ssp245_2050:'SSP2–4.5',ssp585_2050:'SSP5–8.5'};
const regionLabels: Record<string,[string,string]> = {Global:['全球','Global'],Caribbean:['加勒比海','Caribbean'],GBR:['大堡礁','Great Barrier Reef'],Southeast_Asia:['东南亚','Southeast Asia']};
const taxa: Record<string,[string,string]> = {community:['四类群群落','Four-taxon community'],Acropora:['鹿角珊瑚','Acropora'],Lobophora:['褐藻','Lobophora'],Scarus:['鹦嘴鱼','Scarus'],Cephalopholis:['九棘鲈','Cephalopholis']};
const icons = {overview:LayoutDashboard,future:Globe2,historical:ThermometerSun,conservation:ShieldCheck,data:Database,methods:FlaskConical};
const navLabels: Record<View,[string,string]> = {overview:['研究总览','Overview'],future:['未来风险','Future risk'],historical:['热浪与暴露','Heatwaves & exposure'],conservation:['保护配置','Conservation'],data:['数据与溯源','Data & provenance'],methods:['方法与复现','Methods & reproduction']};
const base = import.meta.env.BASE_URL;
function download(name: string, content: string, mime = 'text/csv;charset=utf-8') {
  const url=URL.createObjectURL(new Blob([content],{type:mime}));
  const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Range({metric,english,bootstrap=false}:{metric:Metric;english:boolean;bootstrap?:boolean}) {
  return <span className="range">{formatPct(metric.min)} — {formatPct(metric.max)}<small>{bootstrap ? (english?'95% bootstrap interval':'95% bootstrap 区间') : (english?'3-member range':'三成员范围')}</small></span>;
}
function CardTitle({title,detail,tag}:{title:string;detail?:string;tag?:string}) {return <div className="card-title"><div><h3>{title}</h3>{detail&&<p>{detail}</p>}</div>{tag&&<span className="tag">{tag}</span>}</div>;}

export default function App() {
  const [data,setData]=useState<DemoData|null>(null);
  const [cells,setCells]=useState<MapCell[]>([]);
  const [error,setError]=useState('');
  const [mapError,setMapError]=useState('');
  const [scenario,setScenario]=useState('ssp585_2050');
  const [region,setRegion]=useState('Global');
  const [view,setView]=useState<View>('overview');
  const [english,setEnglish]=useState(false);
  const [taxon,setTaxon]=useState('community');
  const [search,setSearch]=useState('');
  const [member,setMember]=useState('ensemble');
  const [mobile,setMobile]=useState(false);
  const [downloadOpen,setDownloadOpen]=useState(false);
  const [toast,setToast]=useState('');
  const t=(zh:string,en:string)=>english?en:zh;
  const regionName=(key:string)=>regionLabels[key]?.[english?1:0]??key;
  useEffect(()=>{fetch(`${base}data/demo.json`).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(d=>{if(d.schemaVersion!==1||!d.future?.length)throw new Error('Invalid dataset');setData(d);}).catch(e=>setError(String(e)));},[]);
  useEffect(()=>{const controller=new AbortController();setMapError('');setCells([]);fetch(`${base}data/map_${scenario}.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(setCells).catch(e=>{if(e.name!=='AbortError')setMapError(String(e));});return ()=>controller.abort();},[scenario]);
  useEffect(()=>{document.documentElement.lang=english?'en':'zh-CN';},[english]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);}},[toast]);
  const current:Future|null=useMemo(()=>data?findResult(data.future,scenario,region):null,[data,scenario,region]);
  const selectedMember=current?.members.find(m=>m.member===member);
  const conservation=data?findResult(data.conservation,scenario,region):null;
  const navigate=(next:View)=>{setView(next);setMobile(false);};
  function exportCurrent(){if(!data)return;const rows=data.future.filter(r=>r.scenario===scenario).map(r=>({scenario:r.scenario,region:r.region,quality_reduction_pct:r.quality.mean,quality_member_min_pct:r.quality.min,quality_member_max_pct:r.quality.max,burden_change_pct:r.burden.mean,pressure_change_pct:r.pressure.mean,pressure_member_min_pct:r.pressure.min,pressure_member_max_pct:r.pressure.max}));download(`MHW2Coral_${scenario}_regional.csv`,rowsToCsv(rows));setToast(t('已导出当前情景的真实区域数据','Current scenario data exported'));}
  if(error)return <main className="load-screen"><FileCheck2 size={36}/><h1>Dataset could not be loaded</h1><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></main>;
  if(!data||!current)return <main className="load-screen"><Waves size={42}/><h1>MHW2Coral</h1><p>Loading project data…</p></main>;
  const history=data.historical.filter(r=>r.region===region&&r.taxon===taxon).sort((a,b)=>a.group-b.group);
  const high=history.find(r=>r.group===2)!;
  const metrics = [
    {key:'quality' as const,label:t('共适宜栖息地质量降低','Co-suitability quality reduction'),icon:Leaf,color:'green',unit:t('历史固定域 · 连续 HSI','Fixed historical domain · continuous HSI')},
    {key:'pressure' as const,label:t('微塑料暴露压力变化','Microplastic exposure pressure change'),icon:Waves,color:'coral',unit:t('每单位 HSI 加权栖息地','Per unit HSI-weighted habitat')},
    {key:'burden' as const,label:t('微塑料暴露负担变化','Microplastic exposure burden change'),icon:Layers3,color:'sand',unit:t('HSI × MPEI 的面积积分','Area integral of HSI × MPEI')},
  ];
  const summaryCards=<div className="stats-grid">{metrics.map(m=>{const Icon=m.icon; const value=selectedMember?selectedMember[m.key]:current[m.key].mean;return <article className={`stat-card ${m.color}`} key={m.key}><div className="stat-label">{m.label}<Icon size={18}/></div><strong data-testid={`metric-${m.key}`}>{formatPct(value,m.key!=='quality')}</strong><div className="stat-unit">{m.unit}</div><div className="stat-bottom">{selectedMember?<span>{selectedMember.member.split('_').slice(0,2).join('-').toUpperCase()}</span>:<Range metric={current[m.key]} english={english}/>}</div></article>;})}</div>;
  return <div className="app-shell">
    {mobile&&<button className="sidebar-backdrop" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
    <aside className={`sidebar ${mobile?'open':''}`}>
      <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview');}}><div className="brand-mark"><Waves size={26}/></div><div>MHW2Coral<span>ECOSYSTEM RESEARCH</span></div></a>
      <div className="nav-kicker">{t('研究工作台','RESEARCH WORKSPACE')}</div>
      <nav>{(Object.keys(navLabels) as View[]).map(key=>{const Icon=icons[key];return <button key={key} className={`nav-item ${view===key?'active':''}`} onClick={()=>navigate(key)} aria-current={view===key?'page':undefined}><Icon size={19}/><span>{navLabels[key][english?1:0]}</span>{view===key&&<span className="nav-dot"/>}</button>;})}</nav>
      <div className="sidebar-project"><div className="project-icon"><Leaf size={18}/></div><h4>{t('海洋热浪 × 微塑料','Marine heatwaves × Microplastics')}</h4><p>{t('珊瑚礁群落的复合生态风险','Compound ecological risk in coral reef communities')}</p><span>NKU Hu Lab</span></div>
      <a className="repo-link" href="https://github.com/NKUHuLab/MHW2CoralEcoSys" target="_blank" rel="noreferrer"><ExternalLink size={16}/>{t('项目仓库','Project repository')}<ArrowUpRight size={14}/></a>
      <div className="sidebar-bottom"><span className="status-dot"/>{t('真实主线数据子集','Actual project data subset')}<small>Demo v1.0</small></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="breadcrumbs"><button className="mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={20}/></button><span>{t('生态风险研究平台','Ecological risk research')}</span><span className="crumb-slash">/</span><strong>{navLabels[view][english?1:0]}</strong></div><div className="top-actions"><span className="demo-pill"><span/>{t('真实数据 DEMO','REAL-DATA DEMO')}</span><button className="language-button" onClick={()=>setEnglish(!english)} aria-label="Switch language">{english?'中文':'EN'}</button><div className="avatar">HU</div></div></header>
      <main className="workspace">
        <section className="page-heading"><div><div className="eyebrow">MARINE HEATWAVES & CORAL ECOSYSTEMS</div><h1>{view==='overview'?t('珊瑚礁群落的复合风险','Compound risks to coral reef communities'):navLabels[view][english?1:0]}</h1><p>{view==='historical'?t('历史热浪分组与实际模型暴露结果 · 1993–2022','Historical heatwave groups and actual modelled exposure · 1993–2022'):view==='data'?t('从项目原始结果表到每一项展示指标','Trace every displayed metric to its project result table'):t('全球四类群共适宜性与微塑料暴露 · 1993–2022 → 2045–2055','Global four-taxon co-suitability and microplastic exposure · 1993–2022 → 2045–2055')}</p></div><button className="button primary" onClick={()=>setDownloadOpen(true)}><ArrowDownToLine size={16}/>{t('导出数据','Export data')}</button></section>
        <section className="filter-bar"><div className="filter-scenarios"><span className="filter-label">{t('气候情景','Climate scenario')}</span><div className="segmented">{SCENARIOS.map(s=><button key={s} onClick={()=>setScenario(s)} className={scenario===s?'selected':''} aria-pressed={scenario===s}>{scenarios[s]}</button>)}</div></div><div className="filter-region"><Globe2 size={16}/><label htmlFor="region">{t('研究区域','Region')}</label><select id="region" value={region} onChange={e=>setRegion(e.target.value)}>{REGIONS.map(r=><option key={r} value={r}>{regionName(r)}</option>)}</select><ChevronDown size={14}/></div><span className="filter-period">{view==='historical'?'1993–2022':'2045–2055'}</span></section>

        {(view==='overview'||view==='future')&&<>
          {view==='future'&&<div className="inline-control"><label htmlFor="member">{t('显示气候成员','Climate member')}</label><select id="member" value={member} onChange={e=>setMember(e.target.value)}><option value="ensemble">{t('三成员平均与范围','Three-member mean & range')}</option>{current.members.map(m=><option key={m.member} value={m.member}>{m.member}</option>)}</select></div>}
          {summaryCards}
          <div className="analysis-grid"><article className="panel map-panel"><CardTitle title={t('未来共适宜栖息地质量降低','Future co-suitability quality reduction')} detail={`${scenarios[scenario]} · ${t('2045–2055 对比 1993–2022','2045–2055 versus 1993–2022')}`} tag={t('三成员栅格均值','Ensemble-mean raster')}/>{mapError?<div className="map-error">{t('地图读取失败','Map failed to load')}: {mapError}</div>:<ReefMap cells={cells} region={region} onRegion={setRegion} english={english}/>}<div className="map-footer"><span><Globe2 size={13}/>{t('0.083° 来源 → 1° 显示聚合','0.083° source → 1° display aggregation')}</span><button onClick={()=>setRegion('Global')}>{t('重置全球视图','Reset to global')}<ArrowRight size={13}/></button></div></article>
          <article className="panel scenario-panel"><CardTitle title={t('情景间栖息地质量比较','Habitat quality across scenarios')} detail={regionName(region)} tag={t('三模型','3 models')}/><ScenarioBars rows={SCENARIOS.map(s=>({name:scenarios[s],metric:findResult(data.future,s,region).quality}))} selected={SCENARIOS.indexOf(scenario)} label="Habitat quality reduction across scenarios"/><div className="chart-note"><span className="legend-square"/>{t('均值','Mean')}<span className="whisker">↔</span>{t('成员最小–最大值','Member min–max')}</div><div className="insight"><Leaf size={17}/><p>{t('当前区域在三个情景下的质量变化，使用同一历史栖息地域计算。','Scenario comparisons use the same fixed historical habitat domain.')}</p></div><div className="taxon-strip"><span>Acropora</span><span>Lobophora</span><span>Scarus</span><span>Cephalopholis</span></div></article></div>
          <div className="secondary-grid"><article className="panel"><CardTitle title={t('剩余栖息地的暴露压力','Exposure pressure in remaining habitat')} detail={`${scenarios[scenario]} · ${t('三成员均值及范围','Three-member mean and range')}`}/><IntervalChart rows={REGIONS.map(r=>({name:regionName(r),metric:findResult(data.future,scenario,r).pressure,active:r===region}))} label="Regional MPEI pressure change" color="#ca7656"/><p className="panel-footnote">{t('暴露压力 = 暴露负担 ÷ HSI 加权栖息地面积。','Exposure pressure = exposure burden ÷ HSI-weighted habitat area.')}</p></article><article className="panel story-panel"><CardTitle title={t('读懂负担与压力','Understanding burden and pressure')} tag="MPEI"/><div className="story-number"><span>{t('未来暴露压力（三成员均值）','Future pressure (ensemble mean)')}</span><strong>{current.futurePressure.toExponential(2)}<small>kg m⁻³</small></strong></div><div className="pressure-track"><span>{t('历史','Historical')}</span><div style={{width:`${current.historicalPressure/Math.max(current.historicalPressure,current.futurePressure)*100}%`}}/><b>{current.historicalPressure.toExponential(2)}</b></div><div className="pressure-track future"><span>{t('未来','Future')}</span><div style={{width:`${current.futurePressure/Math.max(current.historicalPressure,current.futurePressure)*100}%`}}/><b>{current.futurePressure.toExponential(2)}</b></div><p>{t('负担同时取决于暴露强度和适宜栖息地面积。适宜栖息地收缩时，面积积分的负担可以下降，而剩余栖息地的单位暴露压力上升。','Burden depends on both exposure intensity and suitable habitat area. Habitat contraction can reduce integrated burden while exposure pressure rises in remaining habitat.')}</p><button className="text-link" onClick={()=>navigate('methods')}>{t('查看指标定义与方法','Read metric definitions')}<ArrowUpRight size={14}/></button></article></div>
          {view==='future'&&<article className="panel"><CardTitle title={t('成员结果明细','Individual member results')} detail={t('先计算每个成员的百分比变化，再计算成员均值','Percentage changes are computed per member before averaging')}/><div className="table-scroll"><table><thead><tr><th>{t('气候成员','Climate member')}</th><th>{t('质量降低','Quality reduction')}</th><th>{t('负担变化','Burden change')}</th><th>{t('压力变化','Pressure change')}</th></tr></thead><tbody>{current.members.map(m=><tr key={m.member}><td>{m.member}</td><td>{formatPct(m.quality)}</td><td>{formatPct(m.burden,true)}</td><td>{formatPct(m.pressure,true)}</td></tr>)}</tbody></table></div></article>}
        </>}

        {view==='historical'&&<>
          <div className="lineage-note"><ThermometerSun size={19}/><div><strong>{t('历史分析：54-tracer 固定 MPEI','Historical analysis: fixed 54-tracer MPEI')}</strong><p>{t('MPEI 平均期为1993–2019，HSI 与热浪分组为1993–2022。本页保留独立数据沿革。','MPEI is averaged over 1993–2019; HSI and MHW grouping cover 1993–2022. This page retains its separate historical lineage.')}</p></div></div>
          <div className="taxon-selector">{Object.entries(taxa).map(([key,name])=><button key={key} onClick={()=>setTaxon(key)} className={taxon===key?'selected':''}>{name[english?1:0]}</button>)}</div>
          <div className="secondary-grid"><article className="panel"><CardTitle title={t('热浪分组的暴露差异','Exposure across heatwave groups')} detail={`${regionName(region)} · ${taxa[taxon][english?1:0]}`}/><IntervalChart rows={history.map(r=>({name:[t('低热浪（基准）','Low MHW (reference)'),t('中热浪','Middle MHW'),t('高热浪','High MHW')][r.group],metric:{mean:r.change,min:r.min,max:r.max},active:r.group===2}))} label="MHW group exposure contrasts with 95% bootstrap intervals"/><p className="panel-footnote">{t('2,000次循环四年移动块 bootstrap 的95%区间；每组10年。','95% intervals from 2,000 circular four-year moving-block bootstrap draws; 10 years per group.')}</p></article><article className="panel story-panel"><CardTitle title={t('高热浪相对低热浪','High versus low MHW')}/><div className="historical-value">{formatPct(high.change,true)}<span>{regionName(region)} · {taxa[taxon][english?1:0]}</span></div><Range metric={{mean:high.change,min:high.min,max:high.max}} english={english} bootstrap/><div className="interval-status">{intervalIncludesZero(high.min,high.max)?t('95%区间包含零','95% interval includes zero'):t('95%区间不包含零','95% interval excludes zero')}</div><p>{t('这些分组比较展示模型外部暴露的关联。海温与年份混杂仍限制对热浪独立因果作用的判断。','These group comparisons describe associations in modelled external exposure. SST and year confounding limit independent causal interpretation of MHW.')}</p></article></div>
          <article className="panel"><CardTitle title={t('实际历史数据','Actual historical records')}/><div className="table-scroll"><table><thead><tr><th>{t('分组','Group')}</th><th>MPEI (kg m⁻³)</th><th>{t('相对低热浪变化','Change versus low MHW')}</th><th>{t('95%区间','95% interval')}</th></tr></thead><tbody>{history.map(r=><tr key={r.group}><td>{[t('低','Low'),t('中','Middle'),t('高','High')][r.group]}</td><td>{r.exposure.toExponential(4)}</td><td>{formatPct(r.change,true)}</td><td>{formatPct(r.min)} — {formatPct(r.max)}</td></tr>)}</tbody></table></div></article>
        </>}

        {view==='conservation'&&conservation&&<>
          <div className="lineage-note"><ShieldCheck size={19}/><div><strong>{t('当前保护配置：2026-09-06修复版','Accepted conservation results: repaired 2026-09-06')}</strong><p>{t('相同入选面积和气候模型支持层级下，将MPEI加入优先级排序。','Add MPEI to prioritization while retaining equal selected reef area and climate-model support tiers.')}</p></div></div>
          <div className="stats-grid conservation-stats"><article className="stat-card green"><div className="stat-label">{t('优先区域重分配','Priority area reallocated')}<ShieldCheck size={18}/></div><strong>{formatPct(conservation.reallocation.mean)}</strong><Range metric={conservation.reallocation} english={english} bootstrap/></article><article className="stat-card sand"><div className="stat-label">{t('入选区域平均MPEI变化','Mean selected-area MPEI change')}<Waves size={18}/></div><strong>{formatPct(conservation.gain.mean,true)}</strong><Range metric={conservation.gain} english={english} bootstrap/></article><article className="stat-card neutral"><div className="stat-label">{t('有效bootstrap重复','Effective bootstrap replicates')}<Activity size={18}/></div><strong>{region==='GBR'?'991':'1,000'}</strong><div className="stat-unit">{t('联合模型与5°空间块抽样','Joint climate-member and 5° spatial-block resampling')}</div></article></div>
          <div className="secondary-grid"><article className="panel"><CardTitle title={t('区域重分配比例','Regional priority reallocation')} detail={t('完整数据点估计与95%百分位区间','Full-data estimates and 95% percentile intervals')}/><IntervalChart rows={REGIONS.map(r=>({name:regionName(r),metric:findResult(data.conservation,scenario,r).reallocation,active:r===region}))} signed={false} label="Conservation priority area reallocation"/></article><article className="panel"><CardTitle title={t('MPEI排序带来的变化','Change after adding MPEI prioritization')} detail={t('入选礁区的支持加权平均MPEI','Support-weighted mean MPEI in selected reef areas')}/><IntervalChart rows={REGIONS.map(r=>({name:regionName(r),metric:findResult(data.conservation,scenario,r).gain,active:r===region}))} color="#bc8053" label="Conservation MPEI change with 95% intervals"/></article></div>
          <div className="method-callout"><FileCheck2 size={20}/><p>{t('全球MPEI变化区间包含零。此结果比较两种优先配置的暴露排序，不代表净化效果、已实施保护成效或MPEI降低。','Global MPEI-change intervals include zero. These results compare exposure ranking under two priority configurations; they do not measure pollution removal, realized protection or MPEI reduction.')}</p></div>
        </>}

        {view==='data'&&<>
          <div className="data-intro"><div><Database size={30}/><h2>{t('9个真实源文件','9 actual source files')}</h2><p>{t('6张结果表、3份GeoTIFF。原值完整保留，附SHA-256及项目相对来源。','Six result tables and three GeoTIFFs, unchanged copies with SHA-256 and project-relative provenance.')}</p></div><div className="check-box"><Check size={20}/><strong>{data.checks.numericComparisons}</strong><span>{t('数值复算比较通过','numerical reproduction comparisons passed')}</span></div></div>
          <div className="search-box"><Search size={17}/><input aria-label="Search source files" placeholder={t('搜索文件名或数据来源…','Search filenames or source paths…')} value={search} onChange={e=>setSearch(e.target.value)}/></div>
          <div className="source-list">{data.provenance.files.filter(f=>(f.file+' '+f.project_relative_source).toLowerCase().includes(search.toLowerCase())).map(f=><article className="source-card" key={f.file}><div className="source-icon">{f.file.endsWith('.tif')?<Globe2 size={22}/>:<Database size={22}/>}</div><div className="source-main"><h3>{f.file.split('/').at(-1)}</h3><p>{f.project_relative_source}</p><div className="source-meta"><span>{(f.bytes/1024).toFixed(1)} KB</span>{f.rows!==undefined&&<span>{f.rows} {t('记录','records')}</span>}<span>{t('项目派生结果','Derived project result')}</span></div><details><summary>SHA-256</summary><code>{f.sha256}</code></details></div><a className="icon-button" href={`${base}data/source/${f.file.split('/').at(-1)}`} download aria-label={`Download ${f.file.split('/').at(-1)}`}><ArrowDownToLine size={19}/></a></article>)}</div>
          {!data.provenance.files.some(f=>(f.file+' '+f.project_relative_source).toLowerCase().includes(search.toLowerCase()))&&<div className="empty-state">{t('未找到匹配文件','No matching files')}</div>}
        </>}

        {view==='methods'&&<>
          <div className="workflow-grid">{[{n:'01',title:t('真实数据','Actual data'),text:t('冻结结果表、成员结果与原始派生栅格','Accepted tables, member results and original derived rasters'),Icon:Database},{n:'02',title:t('复算核验','Reproduce & check'),text:t('逐成员百分比计算、均值及范围核对','Per-member percentages, means and range reconciliation'),Icon:FileCheck2},{n:'03',title:t('可视化展示','Visual exploration'),text:t('区域、情景、类群与不确定性切换','Regions, scenarios, taxa and distinct uncertainty intervals'),Icon:Globe2},{n:'04',title:t('导出与追溯','Export & trace'),text:t('下载真实表格和GeoTIFF，核对哈希','Download actual tables and GeoTIFFs; check hashes'),Icon:ArrowDownToLine}].map(item=><article className="workflow-card" key={item.n}><span>{item.n}</span><item.Icon size={22}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div>
          <article className="panel methods-panel"><CardTitle title={t('三个指标，三种解释','Three metrics, three interpretations')}/><div className="definition"><strong>{t('共适宜质量','Co-suitability quality')}</strong><code>Q = Σ Aᵢ × (HSI₁ᵢ × HSI₂ᵢ × HSI₃ᵢ × HSI₄ᵢ)¹/⁴</code><p>{t('固定历史域的连续质量面积积分，单位km²·HSI。不是珊瑚覆盖率或生态损失概率。','Continuous quality integrated over the fixed historical domain, in km²·HSI. This is not coral cover or an ecological loss probability.')}</p></div><div className="definition"><strong>{t('微塑料暴露负担','Microplastic exposure burden')}</strong><code>B = Σ Aᵢ × HSIᵢ × MPEIᵢ</code><p>{t('在对应时期的OR10共适宜栖息地内积分，单位kg·m⁻³·km²。','Integrated within period-specific OR10 co-suitable habitat, in kg·m⁻³·km².')}</p></div><div className="definition"><strong>{t('微塑料暴露压力','Microplastic exposure pressure')}</strong><code>P = B / Σ Aᵢ × HSIᵢ</code><p>{t('单位HSI加权栖息地的外部暴露指标，单位kg·m⁻³。MPEI不是生物内剂量或毒理效应。','External exposure per unit HSI-weighted habitat, in kg·m⁻³. MPEI is not internal dose or toxicological effect.')}</p></div></article>
          <div className="secondary-grid"><article className="panel methods-panel"><CardTitle title={t('计算与数据沿革','Calculation and lineage')}/><ul><li>{t('未来：1993–2022和2045–2055的36-tracer s1–s4时期平均场。','Future: period-matched 36-tracer s1–s4 means for 1993–2022 and 2045–2055.')}</li><li>{t('各SSP共用同一未来MPEI场，情景差异来自栖息地。','SSPs share one future MPEI field; scenario differences arise from habitat projections.')}</li><li>{t('Figure 4暴露面板未应用严格MESS筛选；保护配置应用OR10与MESS支持层级。','Figure 4 exposure panels do not use strict MESS screening; conservation uses OR10 and MESS support tiers.')}</li><li>{t('三成员范围不是95%置信区间。历史和保护配置的bootstrap区间分别显示。','Three-member ranges are not 95% confidence intervals. Historical and conservation bootstrap intervals are displayed separately.')}</li><li>{t('地图对76,635个有效0.083°格点做一度内无权算术平均，仅用于显示。','The map averages 76,635 valid 0.083° cells into one-degree bins for display only.')}</li></ul></article><article className="panel methods-panel"><CardTitle title={t('一键复现','Reproduce the demo')} detail={t('核心数值流程仅需Python标准库','The numerical core uses only the Python standard library')}/><pre><code>python analysis/run_demo.py{`\n`}python -m unittest discover -s tests{`\n\n`}npm ci{`\n`}npm run build{`\n`}npm run preview</code></pre><p>{t('outputs/生成复算结果和验证报告。该demo复现选定结果表，不重新训练MaxEnt或运行完整海洋模式。','The outputs/ directory contains recomputed results and validation. This demo reproduces selected result tables; it does not retrain MaxEnt or rerun the full ocean model.')}</p><a className="text-link" href="https://github.com/NKUHuLab/MHW2CoralEcoSys" target="_blank" rel="noreferrer">{t('查看源代码与运行说明','Source code & instructions')}<ArrowUpRight size={14}/></a></article></div>
        </>}

        {(view==='overview'||view==='future')&&<article className="panel regional-table"><CardTitle title={t('区域风险摘要','Regional risk summary')} detail={`${scenarios[scenario]} · ${t('四个区域不是互斥分区，请勿求和','Regions overlap; do not sum these records')}`} tag={t('实际主线结果','Accepted results')}/><div className="table-scroll"><table><thead><tr><th>{t('研究区域','Region')}</th><th>{t('质量降低','Quality reduction')}</th><th>{t('暴露负担变化','Burden change')}</th><th>{t('暴露压力变化','Pressure change')}</th><th>{t('压力成员范围','Pressure member range')}</th><th/></tr></thead><tbody>{data.future.filter(r=>r.scenario===scenario).map(r=><tr key={r.region} className={r.region===region?'highlight-row':''}><td><span className="table-region-dot"/>{regionName(r.region)}</td><td>{formatPct(r.quality.mean)}</td><td>{formatPct(r.burden.mean,true)}</td><td className={r.pressure.mean>0?'positive-change':'negative-change'}>{formatPct(r.pressure.mean,true)}</td><td>{formatPct(r.pressure.min)} — {formatPct(r.pressure.max)}</td><td><button onClick={()=>{setRegion(r.region);navigate('future');}} aria-label={`${t('查看','Explore')} ${regionName(r.region)}`}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div></article>}
        <footer className="workspace-footer"><span>MHW2CoralEcoSys · NKU Hu Lab</span><span>{t('数据主线：2026-09-07 · demo整理：2026-10-06','Accepted lineage: 2026-09-07 · demo curated: 2026-10-06')}</span><button onClick={()=>navigate('data')}>{t('查看来源','View provenance')}<ArrowUpRight size={12}/></button></footer>
      </main>
    </div>
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {downloadOpen&&<div className="modal-backdrop" onClick={()=>setDownloadOpen(false)}><section className="download-modal" role="dialog" aria-modal="true" aria-labelledby="download-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDownloadOpen(false)} aria-label="Close export dialog"><X size={20}/></button><div className="modal-icon"><ArrowDownToLine size={26}/></div><h2 id="download-title">{t('导出实际研究数据','Export actual research data')}</h2><p>{t('结果值和不确定性字段保留。源文件可以在“数据与溯源”中逐项下载。','Exports retain result values and uncertainty fields. Download individual source files from Data & provenance.')}</p><button className="button primary" onClick={()=>{exportCurrent();setDownloadOpen(false);}}><ArrowDownToLine size={16}/>{t('当前情景区域摘要 CSV','Current-scenario regional CSV')}</button><button className="button secondary" onClick={()=>{download('MHW2Coral_demo.json',JSON.stringify(data,null,2),'application/json');setDownloadOpen(false);}}>{t('完整demo结果 JSON','Complete demo results JSON')}</button><button className="text-link" onClick={()=>{navigate('data');setDownloadOpen(false);}}>{t('浏览原始结果表与GeoTIFF','Browse original tables & GeoTIFFs')}<ArrowRight size={15}/></button></section></div>}
  </div>;
}
